export const DETECTED_SCREEN_SIZE = 'DETECTED_SCREEN_SIZE';

export const START_GET_CATEGORIES = 'START_GET_CATEGORIES';
export const SUCCESS_GET_CATEGORIES = 'SUCCESS_GET_CATEGORIES';
export const FAILED_GET_CATEGORIES = 'FAILED_GET_CATEGORIES';
export const HANDLE_SELECTED_CATEGORY = 'HANDLE_SELECTED_CATEGORY';

export const START_GET_CATS = 'START_GET_CATS';
export const SUCCESS_GET_CATS = 'SUCCESS_GET_CATS';
export const FAILED_GET_CATS = 'FAILED_GET_CATS';
export const HANDLE_LOAD_MORE = 'HANDLE_LOAD_MORE';